/* Second enrichment pass: verifies the remaining entries against Japanese sources
   and adds new layers (dishes, sushi, vegetables and citrus, rice, tea, soy). */

/* ---------- MISO / DASHI ---------- */
P("Echigo miso", {
  text: "A red, dry-style rice miso, also called 'ukikoji miso' because whole polished-rice koji floats as visible grains. The beans are steamed, mixed with salt while still warm and minced, the koji is made without salting down, and extra water is driven off. Jouetsu uses more koji, so the grains show more; the Niigata city area favours a vivid red.",
  craft: "Judged on bright red colour and clean fermentation aroma. It goes into shokkara-ni, kensan-yaki and noppei soup.",
  src: [["Wikipedia (ja): Echigo miso", "https://ja.wikipedia.org/wiki/%E8%B6%8A%E5%BE%8C%E5%91%B3%E5%99%8C"], ["Miso Sommelier: Echigo miso", "https://miso-sommelier.com/category1/entry11.html"]] });
P("Hida hoba miso", {
  text: "Foresters in Hida used a dried magnolia (hoba) leaf as a plate and grilled miso on it. Today it is grilled with scallions, mushrooms and Hida beef. The leaf is said to have antibacterial properties and lends its fragrance.",
  src: [["MAFF: hoba miso", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/38_10_gifu.html"], ["Made in Local: hoba miso", "https://madeinlocal.jp/area/gifu/knowledge/020"]] });

/* ---------- SALT, VINEGAR & MORE ---------- */
P("Kurozu (black vinegar)", {
  text: "Fukuyama (Kirishima, Kagoshima) ferments rice, koji and water in outdoor clay pots, a method running about 200 years. The common line is 6 months or more of fermentation and 6 more of ageing, though some makers age for 3 years or more. The JAS definition of kurozu requires 180 g or more of brown rice or barley per litre and a brown to black-brown colour. It carries a Geographical Indication.",
  src: [["GI portal: Kagoshima tsubozukuri kurozu", "https://pd.jgic.jp/register/entry/7.html"], ["Uto Jozo: how kurozu is made", "https://utojouzou.jp/?mode=f2"], ["Hakko Blend: vinegar basics", "https://www.hakko-blend.com/study/hakkofood/07.html"]] });
P("Sudachi & yuzu", {
  text: "Tokushima grows about 98% of Japan's sudachi (3,999.8 t, 2018 figures). Kochi leads yuzu with about 53% (11,111 t), with Aki, Kitagawa and Kami among the main areas. Both are squeezed on food in place of vinegar.",
  src: [["Urahyoji: sudachi production", "https://urahyoji.com/crops-sudachi/"], ["Oita Prefecture: kabosu vs sudachi", "https://edit.pref.oita.jp/news-columns/1421/"]] });
P("Hon-wasabi", {
  text: "Two crops: sawa (water) wasabi in cold running water, and hatake (field) wasabi, whose biggest producer is Iwate. By root only, Shizuoka ranks first; for roots and stalks together Nagano leads (541.7 t against 465.8 t in 2022), with Azumino around 90% of Nagano's. Grated on sharkskin.",
  src: [["Region-case: wasabi 2022", "https://region-case.com/rank-r4-product-wasabi/"], ["JETRO: wasabi", "https://www.jetro.go.jp/agriportal/pickup/wasabi.html"]] });
P("Yuzu-kosho", {
  text: "A paste of green chilli, yuzu peel and salt. The origin is disputed: the Hikosan area on the Fukuoka-Oita border or Hita in Oita. 'Kosho' is the Kyushu dialect word for chilli, which explains the name. Commercial sales began in 1950 in Soeda, Fukuoka.",
  src: [["Gotouchi-i: yuzukosho", "https://gotouchi-i.jp/ooita-yuzukosho/"], ["Wikipedia (ja): yuzu kosho", "https://ja.wikipedia.org/wiki/%E6%9F%9A%E5%AD%90%E8%83%A1%E6%A4%92"]] });
P("Fish sauces: shottsuru, ishiru, ikanago-shoyu", {
  text: "Japan's 'three great fish sauces': Akita's shottsuru (made from hata-hata, made since the Edo period, the palest and most delicate), Noto's ishiru (sardine or mackerel; 'ishiri' when from squid innards; often cited as the biggest in volume) and Kagawa's ikanago shoyu (sand lance, salt around 28-29%). Records of fish sauce date to the Engishiki.",
  src: [["Gyoshomania: three great fish sauces", "https://gyoshomania.com/2023/03/31/japan3/"], ["Maruichi: fish sauce", "https://www.maruichi.com/delicious/file/post-24.php"], ["Akita Nutrition College: shottsuru", "https://www.akita-eiyo.ac.jp/eiyo-cms/assets/uploads/2020/02/1_3_17.pdf"]] });
ITEMS.push(
  { id: "i_akazu", cat: "salt", name: "Edomae red vinegar", ja: "赤酢（粕酢）", prefs: [13], text: "Red vinegar (akazu, kasuzu) is made from sake lees. Early Edo-period sushi used rice vinegar, and lees vinegar later spread with sushi: it was cheaper than vinegar from rice, which had long been a luxury. Many shops now use white rice vinegar, while Edomae specialists keep akazu.", flavor: "Amber, mellow, umami-rich.", use: "Shari for Edomae nigiri.", craft: "Dates for 'Edomae' vary by source (1680s to 1829), so treat origin years as stories.", src: [["Macaroni: akazu", "https://macaro-ni.jp/88903"], ["Sushikano: akazu", "https://sushikano.jp/en/?p=13262"], ["Wikipedia (ja): Edomae sushi", "https://ja.wikipedia.org/wiki/%E6%B1%9F%E6%88%B8%E5%89%8D%E5%AF%BF%E5%8F%B8"]] },
  { id: "i_gomaabura", cat: "salt", name: "Tamashime sesame oil", ja: "玉締め胡麻油・太白", prefs: [23], text: "Cold-pressed (appaku) sesame oil uses pressure only, with no solvent. Tamashime pressing is an Edo-period method now powered by machine, with less frictional heat. Takemoto Yushi's taihaku oil (founded 1725) is pressed from unroasted sesame, so it is light and neutral. Tamashime is a tiny share, estimated at under 1%.", flavor: "Roasted oil is nutty and deep; taihaku is neutral.", use: "Tempura (taihaku), dressings, finishing oil.", craft: "The 1% figure comes from a co-op article, not an official statistic.", src: [["Takemoto Yushi: taihaku", "https://orderie.jp/component/g/g53352/"], ["Okanna: tamashime", "https://waza2.com/products/167442455"], ["Seikatsu Club: sesame oil", "https://www.s-spirits-shop.jp/?pid=27390717"]] }
);

/* ---------- RAMEN ---------- */
P("Hakodate shio ramen", {
  text: "Part of Hokkaido's three great ramen. A clear shio soup from pork, chicken and kombu (one shop uses Minamikayabe kombu), usually with thinner noodles, though some bowls use medium egg noodles. A piece of fu (wheat gluten) is a local topping.",
  src: [["Hakobura: Hakodate shio ramen", "https://www.hakobura.jp/features/27"], ["Cookpit: Hakodate ramen", "https://cookpit.jp/local-ramen-guide/gotochi-list/hakodateramen/"]] });
P("Tsugaru niboshi ramen", {
  text: "A niboshi-forward shoyu soup, with kombu, pork and chicken bones, and medium-thin curly noodles. Whatever the tare (shoyu, miso or salt), niboshi is the base.",
  src: [["Cookpit: Tsugaru ramen", "https://cookpit.jp/local-ramen-guide/gotochi-list/tsugaruramen/"], ["Amazing Aomori", "https://aomori-tourism.com/photos/detail_80.html"]] });
P("Yamagata hiyashi ramen", {
  text: "Born at Sakaeya Honten in Yamagata around 1952 (Showa 27), when a customer asked for ramen as cold as summer soba. The fat was reworked so it would not congeal when chilled, and the soup reportedly has a hint of La France pear juice. Its founding year is given as 1932 in some sources.",
  src: [["Favy: Sakaeya hiyashi ramen", "https://www.favy.jp/topics/27925"], ["Walkerplus: Sakaeya", "https://www.walkerplus.com/article/171816/"]] });
P("Yokohama iekei", {
  text: "Traced to Yoshimuraya, opened in 1974 in Yokohama by Yoshimura Minoru, a former truck driver. A tonkotsu-and-chicken soup with a strong shoyu tare, chicken oil, medium-thick Sakai Seimen noodles, and nori, spinach and chashu.",
  src: [["Cookpit: history of iekei", "https://cookpit.jp/ramen-jouhoukyoku/ramen-jouhoukyoku-86904/"], ["Ramenmogi: iekei guide", "https://ramenmogi.com/iekei-ramen-guide/"]] });
P("Tsubame-Sanjo seabura", {
  text: "The original is Koshu Hanten (its predecessor dates to 1932-34; sources differ), founded by Xu Changxing from Zhejiang. A back-fat-covered shoyu soup with niboshi, udon-thick noodles and chopped onion, popular with metal-workers. Nagaoka has its own style: ginger shoyu, said to date to Aoshima Shokudo in the late 1960s; the ginger is explained either as masking pork odour or warming people in the cold.",
  src: [["Niigata Kanko: Tsubame seabura", "https://niigata-kankou.or.jp/blog/500"], ["Nakagawa Masashichi story: Koshu Hanten", "https://story.nakagawa-masashichi.jp/5130"], ["Cookpit: Nagaoka ginger ramen", "https://cookpit.jp/local-ramen-guide/gotochi-list/nagaokashoga/"]] });
P("Taiwan ramen", {
  text: "Created at Misen Imaike in Nagoya by Guo Mingyou, a Taiwanese chef, from Tainan danzai noodles. Chicken-based shoyu soup topped with minced meat stir-fried with chilli and garlic, bean sprouts and chives. There is no such dish in Taiwan.",
  src: [["Jalan: Misen Taiwan ramen", "https://www.jalan.net/news/article/312639/"], ["Misen: original Taiwan ramen", "https://www.misen.ne.jp/ramen"]] });
P("Kyoto kotteri", {
  text: "Two currents. Daiichi Asahi (open since 1947) serves a pork-bone shoyu soup with Kujo negi. 'Seabura chacha' ramen, a chicken-based soup with scattered back fat, is credited to Masutani. Thick, viscous 'kotteri' bowls such as Tenkaippin form a third family.",
  src: [["Wikipedia (ja): Kyoto ramen", "https://ja.wikipedia.org/wiki/%E4%BA%AC%E9%83%BD%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3"], ["Ramenmogi: Daiichi Asahi", "https://ramenmogi.com/daiichi-asahi-kyoto-ramen/"]] });
P("Tottori gyukotsu", {
  text: "Beef-bone ramen, very rare nationally, concentrated in central and western Tottori. Shoyu or salt, curly noodles, simple toppings; a sweet beef fat but a clean finish.",
  src: [["Tottori Guide: gyukotsu ramen", "https://www.tottori-guide.jp/828/829/1805/8425.html"], ["Itmedia nlab: gyukotsu ramen", "https://nlab.itmedia.co.jp/research/articles/3123775/"]] });
P("Kumamoto ramen", {
  text: "Pork bone plus chicken, with noodles thicker than Hakata's or Nagahama's. The signature is mayu (ma-yu), garlic fried black in lard and vegetable oil; Keika is credited as the origin. Hakata uses raw garlic, Kumamoto fries it for a roasted fragrance.",
  src: [["Ramen Museum: Kumamoto ramen", "https://www.raumen.co.jp/rapedia/study_japan/study_raumen_kumamoto.html"], ["Favy: Keika's ma-yu", "https://www.favy.jp/topics/28988"]] });
P("Kagoshima ramen", {
  text: "A light tonkotsu with chicken bones and vegetables, semi-cloudy rather than milky like Kurume. Noodles are whitish, made without kansui, and many shops serve pickled daikon.",
  src: [["Cookpit: Kagoshima ramen", "https://cookpit.jp/local-ramen-guide/gotochi-list/kagoshimaramen/"], ["Nikkei: Kagoshima ramen", "https://www.nikkei.com/article/DGXZQOJC099QV0Z00C26A7000000/"]] });

/* ---------- NOODLES ---------- */
P("Mizusawa udon & okkirikomi", {
  text: "Mizusawa udon (Ikaho, Shibukawa) uses only flour, salt and Mizusawa water, no egg, and is translucent and firm. One house, Osawaya, runs 27 steps over two days. Its roots are tied to the Mizusawa temple's pilgrims: the dates differ, from 1,300 years to the 1576 stone steps of Ikaho. Counted with Sanuki and Inaniwa among the 'three great udon'.",
  src: [["Gunma Kanko: Mizusawa udon", "https://gunma-kanko.jp/features/255"], ["MAFF: Mizusawa udon", "https://www.maff.go.jp/j/pr/aff/1610/n_search.html"]] });
P("Miwa, Ibonoito & Shodoshima somen", {
  text: "Miwa somen is said to be over 1,200 years old (a Omiwa shrine tradition) and is a registered GI; repeated ripening ('umashi') helps it survive boiling. Shodoshima's hand-pulled somen came from Miwa about 400 years ago and uses local sesame oil on the dough, giving a faint yellow colour. Ibonoito is the Harima (Hyogo) brand, counted as one of the three great somen.",
  src: [["MAFF: Miwa somen", "https://www.maff.go.jp/j/keikaku/syokubunka/traditional-foods/menu/miwa_soumen.html"], ["GI portal: Miwa somen", "https://pd.jgic.jp/register/entry/12.html"], ["Shimazen: Shodoshima somen", "https://shimazen.co.jp/soumen/history"]] });
P("Champon & sara udon", {
  text: "Shikairo, opened in Nagasaki in 1899, created 'shina udon' for Chinese students, modelled on Fujian tangrousi mian: cheap and nourishing. Sara udon came from Chin Heijun's shop; one explanation is that it was made with less soup to avoid spills in delivery. Nagasaki now distinguishes thick and fried thin noodles.",
  src: [["Shikairo official", "https://shikairou.com/"], ["Nagasaki City: champon and sara udon", "https://www.city.nagasaki.lg.jp/nagazine/hakken0310/index.html"], ["MAFF: sara udon", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/46_7_nagasaki.html"]] });
P("Fujinomiya & Yokote yakisoba", {
  text: "Fujinomiya yakisoba (Shizuoka, post-war) has firm steamed noodles with the boiling step skipped, niku-kasu (rendered pork back fat) and a dusting of fish dashi powder. Yokote yakisoba (Akita, about 1950) is topped with a single-sided fried egg and fukujinzuke, uses boiled straight square noodles and a sweet Worcester-style sauce with dashi.",
  src: [["Fujinomiya Yakisoba Gakkai", "https://umya-yakisoba.com/fujinomiyayakisoba/"], ["Magokoro Care: Yokote yakisoba", "https://magokoro-care-shoku.com/column/lets-make-yokote-yakisoba/"], ["Smart Access: Yokote yakisoba", "http://www.smart-acs.com/bkyugourmet/akita/05_014.php"]] });
P("Shinshu & Togakushi soba", {
  text: "Nagano is soba country. Togakushi soba is served in 'bocchi-mori', bundled mouthfuls set out on a bamboo tray.",
  src: [["A-Resort: three great soba", "https://www.a-resort.jp/column/149"]] });

/* ---------- MEAT ---------- */
P("Miyazaki & Kagoshima wagyu", {
  text: "Miyazaki beef took the Prime Minister's Award at the National Wagyu Competition ('wagyu Olympics', every five years) in 2012, 2017 and 2022, a record four in a row at the 12th (2022) meet. Kagoshima Kuro-ushi is a GI product (2017) and Kagoshima ranks first for Japanese Black cattle (about 18% share, 2021).",
  src: [["Hinata Miyazaki: 4 straight wins", "https://www.hinata-miyazaki.jp/other/2603/"], ["GI portal: Kagoshima kuro-ushi", "https://pd.jgic.jp/register/entry/58.html"], ["Rakusuru Kurashi: cattle ranking", "https://rakusurukurasi.com/kuroge-wagyu-cattle-ranking-2025/7330/"]] });
P("Sendai gyutan", {
  text: "Credited to Sano Keishiro, whose shop Taisuke opened in 1948 (the tongue is on the menu from 1950 by some accounts). He developed it after meeting tongue stew by a French chef in Tokyo. Several shops use 'Taisuke' names after branch splits.",
  src: [["Date no Kura: gyutan history", "https://datenokura.jp/blogs/column/gyutan-history"], ["Aji Tasuke: history", "https://www.aji-tasuke.co.jp/history.php"]] });
P("Yonezawa & Saga beef", {
  text: "Yonezawa beef is Japanese Black virgin heifers raised in Okitama, shipped at 33 months or older at grade 3 or better, a GI product. Saga beef is JA Saga-raised Japanese Black graded A5, or A4 with BMS 7 or higher.",
  src: [["Yonezawa beef council: definition", "http://www.yonezawagyu.jp/03.html"], ["GI portal: Yonezawa beef", "https://pd.jgic.jp/register/entry/26.html"], ["JA Saga: Saga beef", "http://jasaga.or.jp/agriculture/nousanbutsu/sagagyu"]] });
P("Kurobuta & Okinawan Agu pork", {
  text: "Kagoshima kurobuta is Berkshire pork raised in Kagoshima. Agu is the native Ryukyu pig and is not a Berkshire, so it is not labelled kurobuta. Agu litters are small, four or five piglets.",
  src: [["Kagoshima kurobuta", "https://www.k-kurobuta.com/about/"], ["Tokyo Pork Plus: kurobuta", "https://tokyoporkplus.com/porkguide/kurobuta-what-is/"]] });
P("Jidori chicken", {
  text: "The three great jidori. Hinai-jidori is a first-generation cross of a male Hinai-dori (a national natural monument) with Rhode Island Red. Nagoya Cochin dates to 1905 (Buff Cochin with local fowl). Satsuma-jidori carries the blood of the Satsuma-dori, a national natural monument.",
  src: [["Cookdoor: three great jidori", "https://www.cookdoor.jp/family-restaurant/dictionary/13674_resta_065/"], ["Crex: three great jidori", "https://crexgroup.com/ja/travel/travel/japan-top-three-chicken-brands/"]] });
P("Jingisukan", {
  text: "Mutton arrived with sheep farming in the Taisho era, and breeding stations opened in Takikawa and Sapporo. Takikawa claims the pre-seasoned style; Tsukisamu (Sapporo) grills raw meat and dips it afterwards.",
  src: [["Takikawa City: jingisukan", "https://www.city.takikawa.lg.jp/site/kanko/2218.html"], ["Sorachi: jingisukan", "https://www.sorachi.pref.hokkaido.lg.jp/ts/tss/yama/resource/ta_003.html"]] });
P("Basashi", {
  text: "Raw horse meat. Kumamoto's story ties it to Kato Kiyomasa eating warhorses in the Korean campaign, and it spread in the Meiji era. Southern Shinshu (Nagano) has a horse-eating tradition said to reach back to the Heian period.",
  src: [["MAFF: basashi", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/basashi_kumamoto.html"], ["Tabizine: three great basashi", "https://tabizine.jp/article/636502/"]] });
P("Botan-nabe (boar)", {
  text: "A miso-simmered boar stew of Tamba Sasayama, Hyogo. Hunting opens on 15 November and shops serve from about November; the season runs to March. Since swine fever (2021) local boar has been scarce, so some shops source elsewhere.",
  src: [["Sasayama Tourism: botan-nabe", "https://tourism.sasayama.jp/botannabe/"], ["Kinmata: botan-nabe", "https://www.kinmata.jp/"]] });
P("Yakitori regional styles", {
  text: "Imabari (Ehime): chicken skin pressed on an iron plate, not skewered; began at Gomidori in 1961 and ends with 'senzangi'. Muroran (Hokkaido): pork and onion with yogarashi mustard; the origin shop is Toriyoshi (1937). The pork is usually explained by cost and the town's steel-works.",
  src: [["MAFF: Imabari yakitori", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/imabari_yakitori_ehime.html"], ["Nikkei: Muroran yakitori", "https://www.nikkei.com/article/DGXKZO43314080U9A400C1KNTP00/"], ["Gurutabi: Muroran yakitori", "https://gurutabi.gnavi.co.jp/a/a_3006/"]] });
P("Nakatsu karaage", {
  text: "Moriyama opened in Nakatsu in July 1970 and is cited as the origin of Nakatsu karaage; Usa's Shosuke claims the start of karaage specialty shops.",
  src: [["Moriyama: history of Nakatsu karaage", "https://souhonke-moriyama.com/%E4%B8%AD%E6%B4%A5%E3%81%8B%E3%82%89%E3%81%82%E3%81%92%E3%81%AE%E6%AD%B4%E5%8F%B2/"]] });
P("Chicken nanban", {
  text: "From Nobeoka: fried chicken dipped in sweet vinegar, said to start as a staff meal at the Western restaurant London in the 1950s-60s, without tartar. Ogura (Miyazaki city) also claims it and adds tartar sauce. Nobeoka declared itself the birthplace in 2009.",
  src: [["Miyazaki Prefecture: chicken nanban", "https://www.pref.miyazaki.lg.jp/contents/org/shoko/appeal/jaja/19_03.html"], ["Daily Portal Z: Nobeoka", "https://dailyportalz.jp/kiji/chicken-nanban-hassyo-no-chi"]] });
P("Gyoza towns", {
  text: "In the 2025 household survey Hamamatsu was first for the third year running (4,046 yen per household), ahead of Utsunomiya (3,575) and Miyazaki (3,418). Miyazaki led in 2021, and Utsunomiya was first for 15 years to 2010.",
  src: [["Nikkei: Hamamatsu three in a row", "https://www.nikkei.com/article/DGXZQOCC062RQ0W6A200C2000000/"], ["Hamamatsu City release", "https://www.city.hamamatsu.shizuoka.jp/shise/koho/koho/hodohappyo/2026/2/0603.html"]] });

/* ---------- SEAWEED ---------- */
P("Asakusa nori", {
  text: "The name is debated: nori landed and processed in Asakusa, or once gathered there. Edo-period culture; the paper-making technique for sheet nori is recorded in the Genroku era. Farming in Tokyo Bay ended in 1962 when fishing rights were given up. Since the war a fast-growing species (susabi-nori) replaced the fragile asakusa-nori.",
  src: [["JTCO: Edomae asakusa nori", "https://www.jtco.or.jp/column/readings/?act=detail&id=77"], ["Tokyo Trip: Edomae nori", "https://tokyo-trip.org/encyclopedia/edomae-nori/"]] });
P("Sanriku & Naruto wakame", {
  text: "Sanriku produces about 70% of Japan's wakame, per a fishery association. Iwate was second nationwide in 2024. Naruto wakame was offered as tribute to the court in the Tenpyo and Heian eras; after the 2011 disaster Tokushima briefly became the top producer.",
  src: [["JF Zengyoren: Sanriku wakame", "https://www.zengyoren.or.jp/sanriku_wakame/"], ["Tokushima Pref: Naruto wakame", "https://www.pref.tokushima.lg.jp/file/attachment/78826.pdf"], ["Urahyoji: wakame production", "https://urahyoji.com/wakame-yoshoku/"]] });
P("Okinawa mozuku", {
  text: "Okinawa produces over 99% of Japan's farmed mozuku (99.6% in 2019). The industry began around 1979 and grew from about 1,000 t.",
  src: [["Urahyoji: mozuku production", "https://urahyoji.com/mozuku-yoshoku/"], ["Mozuku association", "https://www.mozukukyo.org/mozuku/"]] });
P("Umibudo (sea grapes)", {
  text: "Kubirezuta, grown on Okinawan farms. Land-based farming was set up by Onna village fishermen's co-op around 1989 or 1994 (sources differ). Output averaged about 332 t a year from 2008 to 2020.",
  src: [["Pride Fish: umibudo", "https://www.pride-fish.jp/JPF/pref/detail.php?pk=1522751118"], ["Orion: umibudo", "https://www.orionbeer.co.jp/story/umibudo/"]] });
P("Ise & Boso hijiki", {
  text: "Ise hijiki is the steamed-and-dried product of the Ise-Shima area. It appears in Edo-period writing as an Ise speciality. Mie, Chiba and Nagasaki are the main producers.",
  src: [["MAFF: Ise hijiki", "https://www.maff.go.jp/j/keikaku/syokubunka/traditional-foods/menu/ise_hiziki.html"]] });
P("Aonori of the Shimanto & Yoshino", {
  text: "Natural suji-aonori from the Shimanto River has been very unstable: three straight years under 3 t after 2005, and no harvest for five years from 2019 until a recent return. The Yoshino River crop relies on natural seeding.",
  src: [["Kochi News: Shimanto aonori", "https://www.kochinews.co.jp/article/detail/822175"], ["PR Times: Yoshino suji-aonori", "https://prtimes.jp/main/html/rd/p/000000003.000189250.html"], ["Shimanto Tourism: aonori", "https://www.shimanto-kankou.com/kanko/eat/aonori.html"]] });
P("Izu tengusa", {
  text: "Tengusa is boiled and set into tokoroten. Output in 2023: Ehime 49.8 t, Shizuoka (Izu) 43.5 t, Tokyo (Izu islands) 14.4 t, Mie 3.8 t. Izu tengusa is hand-gathered by women divers, whose ageing is a worry.",
  src: [["Tokoroten.co.jp: tengusa", "https://www.tokoroten.co.jp/blog/tengusa/"], ["Slow Food Nippon: Izu tokoroten", "https://slowfood-nippon.jp/izu-peninsula-traditional-tokoroten/"]] });

/* ---------- PICKLES ---------- */
P("Nozawana-zuke", {
  text: "Said to descend from Tennoji turnip seed brought from Kyoto by the priest of Kenmeiji around 1756. In the high, snowy climate the root did not swell, but the leaves and stems grew large. Eaten as asa-zuke (fresh) or furu-zuke (sour, turns yellow by spring).",
  src: [["MAFF: nozawana-zuke", "https://www.maff.go.jp/j/keikaku/syokubunka/traditional-foods/menu/nozawana_zuke.html"], ["Nozawa Onsen Tourism", "https://nozawakanko.jp/about/"]] });
P("Natto", {
  text: "In the 2017-19 household survey Fukushima city was first, Morioka second and Mito third; Mito is the famous name but not the top consumer. A 2019 survey of packs per person put Nagano first (25.7), Fukushima second and Mito seventh. Consumption is east-high, west-low.",
  src: [["Sotokoto: natto consumption", "https://sotokoto-online.jp/food/3868"], ["Todo-ran: natto", "https://todo-ran.com/t/kiji/11483"], ["47todofuken: natto", "https://47todofuken-ranking.com/natto/"]] });
P("Umeboshi", {
  text: "Wakayama has been first in ume harvest for 60 straight years: 29,700 t in 2024, down 21,300 t from the year before. Minabe takes about 25% of national harvest and the Nanko variety about 80% of its ume; Nanko comes from Takada Sadakusu's 'Takada ume'. Salt ranges from about 5% to 20% by product, not a fixed standard.",
  src: [["Agara: Wakayama ume 2024", "https://www.agara.co.jp/article/460046"], ["Minabe Town: agriculture", "https://www.town.minabe.lg.jp/shigoto/02/01/2013091300124.html"], ["Wakayama Tourism: Nanko ume", "https://www.wakayama-kanko.or.jp/features/detail_617.html"]] });
P("Kusaya", {
  text: "Dried fish of the Izu islands, soaked in a reused brine. A leading story places the origin in Niijima, where salt was a tax and was saved by reusing the brine, which fermented into kusaya liquid. The liquid is about 8% salt, against 18-20% in a normal dried-fish brine. Six makers remain.",
  src: [["Dancyu: kusaya", "https://dancyu.jp/read/2026_00010299.html"], ["Sakanato: kusaya history", "https://sakanato.jp/444/"], ["Haccola: kusaya", "https://haccola.jp/2018_11_06_1046/"]] });
P("Takana-zuke", {
  text: "Aso takana is made from slender, soft stems that bolt in mid-to-late March, with a regional collective trademark since 2007. The modern plant descends from a green mustard that came from Sichuan around the end of Meiji. Miike takana (Fukuoka) is a different variety.",
  src: [["MAFF: Aso takana-zuke", "https://www.maff.go.jp/j/keikaku/syokubunka/traditional-foods/menu/asotakanaduke.html"], ["Aso Takana: about", "http://www.asotakana.com/whats/"]] });
P("Yamagata dashi", {
  text: "A summer relish of cucumber and eggplant with shiso and myoga, dressed with soy and the vegetables' own mucilage. It belongs to the hot, humid Murayama region.",
  src: [["MAFF: Yamagata dashi", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/dashi_yamagata.html"], ["Yamagata City: dashi", "https://www.city.yamagata-yamagata.lg.jp/kenkofukushi/iryou/shokuiku/1003317/1007211/1003359.html"]] });
P("Awa-bancha & Goishi-cha", {
  text: "Post-fermented teas of Shikoku. Awa-bancha is single-stage lactic-acid fermentation; Goishi-cha takes two stages, mold fermentation of steamed leaves followed by weeks of pickled, anaerobic fermentation. Ehime's Ishizuchi kurocha and Toyama's Batabata-cha complete the Japanese set.",
  src: [["Haccola: Awa-bancha", "https://haccola.jp/2018_06_06_7239/"], ["JST: Goishi-cha and Awa-bancha", "http://jglobal.jst.go.jp/public/201802290900621839"], ["MAFF Aff: post-fermented tea", "https://www.maff.go.jp/j/pr/aff/2204/pdf/aff2204-3.pdf"]] });

/* ---------- SWEETS ---------- */
P("Shingen mochi", {
  text: "Kikyoya's Kikyo Shingen mochi is three pieces of kinako-dusted mochi in a small tub, with a kuromitsu (black sugar syrup) to pour on.",
  src: [["Fujiyamasan: Shingen mochi", "https://fujiyamasan.com/shingenmochi/"]] });
P("Zunda mochi", {
  text: "Mochi coated in mashed edamame, common in southern Tohoku and especially Miyagi. The name is explained as 'mame-uchi' (beating beans), and a legend has Date Masamune mashing edamame in camp. Frozen zunda now makes it available all year, though it is a summer food.",
  src: [["Wikipedia (ja): zunda mochi", "https://ja.wikipedia.org/wiki/%E3%81%9A%E3%82%93%E3%81%A0%E9%A4%85"], ["Zenkaren: zunda mochi", "https://zenkaren.net/archives/18630"]] });
P("Momiji manju", {
  text: "Credited to Takatsudo, from about 1906 (Meiji 39), with Takatsu Tsunesuke named as the maker. A story that Ito Hirobumi's joke inspired the leaf shape cannot be proven.",
  src: [["Hatsukaichi Tourism: Takatsudo", "https://hatsu-navi.jp/restaurants-shopping/takatsudo/"], ["Shinise.tv: Takatsudo", "https://shinise.tv/takatsudo/"]] });
P("Chinsuko & sata andagi", {
  text: "Chinsuko dates from Ryukyu Kingdom times. Theories: a steamed sweet like the Chinese taosu, or Portuguese bolo. The baked form is said to begin in 1908 (Meiji 41) when it was baked in a brick oven for the first time.",
  src: [["Wikipedia (ja): chinsuko", "https://ja.wikipedia.org/wiki/%E3%81%A1%E3%82%93%E3%81%99%E3%81%93%E3%81%86"], ["Marukiyo: history of chinsuko", "https://www.marukiyo.jp/blog/history/5354/"]] });

/* ---------- SAKE ---------- */
P("Miyagi sushi sake", {
  text: "Sake making grew from the Sendai domain under Date Masamune. In 1986 the prefecture declared itself the 'junmai-shu prefecture'. A very high share, about 90-96%, is tokutei-meisho sake. Many brewers use ordinary table rice such as Sasanishiki alongside the local sake rice 'Kura-no-hana'. Style is called clean and dry by some sources and 'full-bodied dry' by others.",
  src: [["Serai: Miyagi junmai", "https://serai.jp/gourmet/1239688"], ["Sake-5: sake by prefecture", "https://sake-5.jp/sake-by-region-prefecture/"], ["Sushi-blog: Miyagi sake", "https://sushi-blog.com/sakelog/pref-miyagi/"]] });
P("Shizuoka ginjo", {
  text: "Called the 'ginjo kingdom'. Shizuoka's own yeast gives a fruity aroma. One of the 'four kings' of Noto toji, Hase Shokichi, brewed Kaiun at Doi Shuzojo in Shizuoka.",
  src: [["Sake-5: sake by prefecture", "https://sake-5.jp/sake-by-region-prefecture/"], ["Nihonmono: Noto toji", "https://nihonmono.jp/article/5439/"]] });
P("Ishikawa: Noto toji", {
  text: "Noto toji is one of the four great toji guilds (with Echigo, Tajima and Nanbu). The 'four kings' are usually named as Noguchi Naohiko (Kikuhime), Naka Saburo (Tengumai, Kurumata), Hase Shokichi (Kaiun, Shizuoka) and Sanpai Koichi (Masuizumi). The style is described as rich and showy.",
  src: [["Mapple: Noto toji", "https://www.mapple.net/articles/bk/14444/"], ["Nihonmono: Noto toji four kings", "https://nihonmono.jp/article/5439/"], ["Serai: Ishikawa sake", "https://serai.jp/gourmet/1230144"]] });
P("Nara: birthplace of sake", {
  text: "Shoryakuji is called the cradle of clear sake and of the bodaimoto starter, a forerunner of kimoto-style starters. The 'Goshu no nikki' of the Muromachi period records 'bodaisen', though it does not describe a starter. The bodaimoto was reconstructed at the start of 1999 and is brewed each January at a bodaimoto festival. The phrase 'birthplace of Japanese sake' emerged from later research.",
  src: [["Shoryakuji: bodaimoto festival", "https://shoryakuji.jp/event/event2.html"], ["Sakestreet: Shoryakuji bodaimoto", "https://sakestreet.com/ja/media/interview-with-shoryakuji-about-bodaimoto"], ["Bodaimoto.org", "https://bodaimoto.org/bodaimoto/"]] });
P("Yamaguchi: Dassai", {
  text: "Asahi Shuzo (now Dassai) in Iwakuni began selling the 23% polished Dassai in 1992. Polishing the rice takes a total of 168 hours, by one account.",
  src: [["Wikipedia (ja): Dassai", "https://ja.wikipedia.org/wiki/%E7%8D%BA%E7%A5%AD_(%E4%BC%81%E6%A5%AD)"], ["Kago-ya: Dassai 23", "https://shop.kago-ya.net/products/%E7%8D%BA%E7%A5%AD-%E7%B4%94%E7%B1%B3%E5%A4%A7%E5%90%9F%E9%86%B8-23"]] });
P("Kochi: Tosa-karakuchi", {
  text: "Kochi is classed with Ehime and Kagawa as 'tanrei karakuchi' in one regional scheme, though classifications vary by source. Made to match katsuo tataki and Tosa banquet food.",
  src: [["Sake-5: sake by prefecture", "https://sake-5.jp/sake-by-region-prefecture/"]] });
P("Saga: Nabeshima", {
  text: "Nabeshima is brewed at Tomisaki Shuzo. Sources disagree about Saga's style: 'rich dry' in one, 'rich sweet' in another.",
  src: [["Sake-5: sake by prefecture", "https://sake-5.jp/sake-by-region-prefecture/"], ["Sushi-blog: sake by prefecture", "https://sushi-blog.com/sakelog/prefectures/"]] });
P("Hokkaido sake", {
  text: "Hokkaido's sake rice: Ginpu (2000), Suisei (low in protein, light) and Kitashizuku (between the two, soft, few off-flavours). Cultivation began with Hatsushizuku in 1998.",
  src: [["Sakestreet: Ginpu", "https://sakestreet.com/ja/media/what-is-ginpu"], ["Hokkaido Sake Association: sake rice", "https://www.hokkaido-sake.or.jp/knowledge/trivia/"], ["Sakebayashi: Kitashizuku", "https://www.sakebayashi.com/sake-sakamaibetsu-kitashizuku"]] });

/* ---------- SHOCHU ---------- */
P("Imo & soba shochu (Miyazaki)", {
  text: "Soba shochu started in 1973 with 'Soba Unkai' from Gokase (then Gokase Shuzo, renamed Unkai Shuzo in 1978). Kirishima Shuzo's Kuro Kirishima (launched 1998 or 1999) is a black-koji sweet-potato shochu, tracing its black koji to the 1916 founding.",
  src: [["Tanoshii Osake: Unkai soba shochu", "https://tanoshiiosake.jp/3995"], ["Tanoshii Osake: soba shochu", "https://tanoshiiosake.jp/9059"], ["Nishinippon: Kuro Kirishima", "https://www.nishinippon.co.jp/yakusake/2022/04/29/kurokirishima/"]] });
P("Mugi-jochu (Oita, Iichiko)", {
  text: "Nikaido launched an all-barley shochu (barley koji too) in 1974. Sanwa Shurui, formed in 1958 by three breweries, launched Iichiko in 1979. Iki is also called the cradle of barley shochu. Atmospheric distillation (90-100 C) keeps richer aroma; vacuum distillation (40-50 C) gives a soft, clean spirit, and solved the burnt smell in rice and barley shochu.",
  craft: "'Oita barley shochu' is a regional collective trademark of the Oita sake brewers' association.",
  src: [["Iichiko: atmospheric vs vacuum", "https://style.iichiko.co.jp/attraction/20220805/0154/"], ["Iichiko: Oita barley shochu", "https://style.iichiko.co.jp/attraction/20230113/0193/"], ["Honkaku Shochu & Awamori: distillation", "https://guide.honkakushochu-awamori.jp/shochu-distilled/"]] });

/* ---------- WHISKY / BEER / WINE ---------- */
P("Akkeshi", {
  text: "Hokkaido's Akkeshi distillery began distilling in 2016 (some lists say 2014), owned by Kenten Jitsugyo, aiming at an Islay-like style.",
  src: [["Liqul: distillery list", "https://liqul.com/upimg/2020/01/jyouryumap2019.pdf"], ["Whisky Taru Blog: distilleries", "https://whisky-taru-blog.com/%E3%80%902026%E5%B9%B4%E7%89%88%E3%80%91%E6%97%A5%E6%9C%AC%E3%81%AE%E3%82%A6%E3%82%A4%E3%82%B9%E3%82%AD%E3%83%BC%E8%92%B8%E7%95%99%E6%89%80%EF%BD%9C%E5%85%A8126%E3%82%AB%E6%89%80%E3%82%92%E8%A7%A3/"]] });
P("Shizuoka Distillery", {
  text: "Gaia Flow's distillery in Aoi ward, Shizuoka city, uses wood-fired direct-heated pot stills, which is very rare worldwide. Start dates vary: 2014 for distilling in one list, 2016 in another.",
  src: [["Shizuoka Distillery: local place", "https://shizuoka-distillery.jp/place/"], ["Whisky Labo: distillery list", "https://whiskylabo.com/japanese-whisky-list/"]] });
P("Mars Shinshu", {
  text: "In Miyada village, Nagano (Kamiina). Dated 1985 in one account. Honbo Shuzo's other distillery, Tsunuki, started in 2016.",
  src: [["Hyotan: Mars whisky", "https://www.hyotan.co.jp/cnt/whisky/mars.html"]] });
P("Mars Tsunuki", {
  text: "Honbo Shuzo's distillery at Kaseda Tsunuki, Minamisatsuma, Kagoshima, started distilling in 2016, with a maturing warehouse on Yakushima. Mars Tsunuki and Akkeshi swapped malt spirit in 2018.",
  src: [["Hyotan: Mars whisky", "https://www.hyotan.co.jp/cnt/whisky/mars.html"], ["Discover Japan: distilleries", "https://discoverjapan-web.com/article/155850"]] });
P("Sapporo Beer", {
  text: "The Kaitakushi Brewery opened on 23 September 1876 under Murahashi Hisanari, with Nakagawa Seibei, who learned brewing in Germany. Hokkaido's cool climate and ice and snow for lagering decided the location.",
  src: [["Sapporo Factory: Kaitakushi brewery", "https://sapporofactory.jp/beer_museum/"], ["Kirin History Museum: Nakagawa Seibei", "https://museum.kirinholdings.com/person/beer/01.html"]] });
P("Echigo Beer", {
  text: "The 1994 tax law revision cut the minimum annual output for a beer licence from 2,000 kL to 60 kL. Echigo Beer in Niigata got its licence in December 1994 and opened Japan's first brewpub in February 1995. Sources differ on which of two companies was 'first'.",
  src: [["Kirin History Museum: 1994 tax change", "https://museum.kirinholdings.com/history/column/bd099_1994.html"], ["Beergirl: Echigo Beer 30 years", "https://beergirl.net/echigo-30th_c/"]] });
P("Koshu wine", {
  text: "In July 2013 'Yamanashi' became Japan's first wine geographical indication, awarded after a sensory panel of the prefectural winemakers' association. Katsunuma sells GI Yamanashi Koshu from Katsunuma-grown grapes.",
  src: [["GI Yamanashi wine", "https://www.wine.or.jp/gi-yamanashi/store/products/list?category_id=11"], ["NTA lecture: Japanese wine", "https://www.nta.go.jp/about/organization/ntc/kokai/pdf/08230910_06.pdf"]] });
P("Umeshu", {
  text: "Wakayama has led ume harvest for 60 straight years, with Minabe designated an 'umeshu special zone'. 'Wakayama umeshu' has a GI.",
  src: [["Tanoshii Osake: Wakayama ume and umeshu", "https://tanoshiiosake.jp/9711"], ["Wakayama Umeshu", "https://www.wakayamaumeshu.jp/column/p_295/"], ["Agara: 60 years #1", "https://www.agara.co.jp/article/460046"]] });

/* ================== NEW LAYERS ================== */
CATS.push(
  { id: "dish", label: "Regional dishes", ja: "郷土料理" },
  { id: "sushi", label: "Sushi styles", ja: "寿司" },
  { id: "veg", label: "Vegetables, citrus & aromatics", ja: "野菜・柑橘・薬味" },
  { id: "rice", label: "Rice", ja: "米" },
  { id: "tea", label: "Tea", ja: "お茶" },
  { id: "soy", label: "Tofu, yuba & konnyaku", ja: "豆腐・湯葉・こんにゃく" }
);
CAT_INTRO.dish = "Dishes carry the logic of their region: a catch that spoils, a salt that was scarce, a festival. Many borders, such as the east-west split in ozoni and oden, follow older fault lines than the prefecture map.";
CAT_INTRO.sushi = "Sushi began as fermented fish in rice (narezushi) and became vinegared and pressed in the Kansai before nigiri took over Edo. Local styles remain along that line.";
CAT_INTRO.veg = "Heritage vegetables and aromatic crops, with real numbers: Tokushima grows about 98% of sudachi, Oita about 98-99% of kabosu, Kochi about half of yuzu, Wakayama most of the budo sansho.";
CAT_INTRO.rice = "Koshihikari alone is a third of Japan's paddy: 33.1% in the 2023 crop, then Hitomebore, Hinohikari and Akitakomachi. Each prefecture's mix says what its kitchens expect from rice.";
CAT_INTRO.tea = "Kagoshima passed Shizuoka in total crude tea output in 2024. The cultivation method sets the type: open field for sencha, about 20 days of shade for gyokuro, about a week for kabusecha, and unrolled tencha for matcha.";
CAT_INTRO.soy = "Soy goes into very different products by region: Kyoto's yuba and fu for tea-ceremony and shojin cooking, Okinawa's firm shima-dofu and Gunma's konjac, which is more than 90% of national output.";

const A = (cat, name, ja, prefs, text, flavor, use, craft, src) => ITEMS.push({ id: "n_" + cat + "_" + ITEMS.length, cat, name, ja, prefs, text, flavor, use, craft, src });

/* ---------- DISHES ---------- */
A("dish", "Kaiseki (tea) vs kaiseki (banquet)", "懐石と会席", [26], "Two meals with the same sound. Chakaiseki (懐石) is the meal served in a tea gathering, and the rice and soup come first. Banquet kaiseki (会席) is the meal for drinking: rice and soup come near the end. Both descend from Muromachi honzen cooking. A typical tea-kaiseki flow is ichiju sansai, then strong dish (shiizakana), hashiarai, hassun and the final yuto and pickles.", "Seasonal, restrained, dashi-led.", "A course for tea (kaiseki) or a banquet (kaiseki).", "Banquet courses go: sakizuke, wanmono, mukozuke, hachizakana, shiizakana, tomezakana, rice and tome-wan, pickles, fruit.", [["President: kaiseki vs kaiseki", "https://president.jp/articles/-/54971?page=1"], ["Kobayashi Foods: kaiseki vs kaiseki", "https://www.kobayashi-foods.co.jp/washoku-no-umami/kaiseki-meeting-meal"], ["Delish Kitchen: kaiseki", "https://delishkitchen.tv/articles/954"]]);
A("dish", "Kaga cuisine: jibu-ni & kaburazushi", "加賀料理（治部煮・かぶら寿し）", [17], "Jibu-ni is duck dredged in flour and simmered in dashi with sudare-fu, lily bulb and shiitake, with wasabi to finish. Kaburazushi packs turnip and fish in salt and rice koji and ferments them.", "Soft, sweet-savoury; kaburazushi tangy.", "Winter festive food.", "The flour coating gives jibu-ni its gloss and thickens the simmering liquid.", [["Kanazawa Tourism: Kaga cuisine", "https://www.kanazawa-kankoukyoukai.or.jp/article/detail_610.html"], ["Notoya: jibu-ni", "https://www.notoya.co.jp/sonota/kanazawa-20.html"], ["Wikipedia (ja): jibu-ni", "https://ja.wikipedia.org/wiki/%E3%81%98%E3%81%B6%E7%85%AE"]]);
A("dish", "Oden: Kanto, Kansai and Shizuoka", "おでん（関東・関西・静岡）", [13, 27, 22], "Kanto oden uses a katsuo dashi with koikuchi shoyu and favours chikuwabu, hanpen and ganmo. Kansai ('Kanto-daki') uses a kombu dashi with usukuchi shoyu and salt, a pale clear broth, with beef tendon, octopus and whale tongue (saezuri). Shizuoka oden is skewered, in a black beef-tendon broth, with black hanpen (sardine or mackerel paste) and sprinkled with aonori and fish powder (dashiko).", "Kanto: dark and strong. Kansai: pale and sweet. Shizuoka: black, with sea-powder.", "Winter street and izakaya food.", "Chikuwabu is eaten only in the Kanto.", [["Olive Hitomawashi: Kanto vs Kansai oden", "https://www.olive-hitomawashi.com/column/2018/11/post-3366.html"], ["Toyo Keizai: oden differences", "https://toyokeizai.net/articles/-/154640"], ["Shizuoka Food Info: Shizuoka oden", "https://fujinokuni.shokunomiyako-shizuoka.pref.shizuoka.jp/culture/article/2492"], ["Lettuce Club: Shizuoka aonori", "https://www.lettuceclub.net/news/article/136809/"]]);
A("dish", "Sukiyaki: Kanto vs Kansai", "すき焼き（関東風・関西風）", [13, 27], "Kanto simmers beef and vegetables in a prepared warishita of soy sauce, mirin, sake, sugar and dashi. Kansai grills the beef first in a hot iron pan, sprinkles sugar, then adds sake and soy, with no warishita. Both are dipped in raw egg.", "Kanto: even and sweet-salty. Kansai: seared beef first.", "Beef sukiyaki at New Year and celebrations.", "The question is grill or simmer.", [["Cookbiz: sukiyaki Kanto vs Kansai", "https://cookbiz.jp/soken/culture/sukiyaki_kantou_kansai/"], ["Rakuten Recipe: sukiyaki", "https://recipe.rakuten.co.jp/news/article/333/"]]);
A("dish", "Ozoni: the east-west mochi line", "お雑煮（角餅と丸餅）", [13, 27, 40], "In the east (Kanto) ozoni is a clear soup with grilled square mochi, chicken and komatsuna. In the west (Kansai) round mochi is boiled in white miso. The dividing line is often drawn at Sekigahara, though some say the Battle of Sekigahara is only the folk explanation. Osaka serves white miso on 1 January and clear soup the day after. Hakata uses a clear soup with ago dashi and yellowtail.", "East: clear and savoury. West: sweet and creamy miso.", "New Year's meal.", "Look at the mochi shape to read the region.", [["Mi-journey: Kanto vs Kansai ozoni", "https://mi-journey.jp/foodie/108810/"], ["Kurashiru: ozoni", "https://www.kurashiru.com/articles/47e5f18f-f5a9-4af8-be7f-6fc3d45a8dc8"], ["Tripa: ozoni", "https://www.nta.co.jp/media/tripa/articles/kDgnz"]]);
A("dish", "Imoni: Yamagata vs Miyagi", "芋煮（山形と宮城）", [6, 4], "Yamagata's imoni is soy-based with beef; Miyagi's is miso-based with pork (usually Sendai miso). Nakayama in Yamagata is called the birthplace: boatmen and traders on the Mogami River cooked dried cod with taro while waiting for cargo. Yamagata city's festival cooks 30,000 servings in a pot 6.5 m across. The Shonai coast of Yamagata uses miso, and Nagai has a horse-meat salt version.", "Yamagata: soy-beefy. Miyagi: miso-pork.", "Riverside autumn gatherings (imonikai).", "The soy-or-miso split follows the prefecture boundary.", [["Macaroni: Miyagi imoni", "https://macaro-ni.jp/47631"], ["Imonikai: imoni map", "https://imonikai.jp/imoni-map/"], ["Hobbytimes: imoni", "https://hobbytimes.jp/article/20170330b.html"]]);
A("dish", "Okonomiyaki: Hiroshima vs Osaka", "お好み焼き（広島風・関西風）", [34, 27], "Osaka mixes batter and ingredients before grilling ('mazeyaki'). Hiroshima layers a thin crepe, cabbage, pork and noodles ('kasaneyaki'), and its ancestor is the issen yoshoku. Osaka versions with noodles mixed in are called 'modan-yaki'.", "Osaka: fluffy. Hiroshima: layered and noodle-heavy.", "Griddle food.", "The two are different techniques, not variations.", [["Mynavi: Osaka vs Hiroshima", "https://news.mynavi.jp/article/20140607-okonomiyaki/"], ["Tenpos: Osaka and Hiroshima", "https://foodmedia.tenpos.com/newstrend/trend/66433/"]]);
A("dish", "Takoyaki, Akashi-yaki & monja", "たこ焼き・明石焼・もんじゃ", [27, 28, 13], "Takoyaki dates to 1935 at Aizuya in Osaka (it started as radio-yaki in 1933); Tomekichi Endo added octopus after hearing of Akashi's tamago-yaki. Aizuya's takoyaki is eaten without sauce. Akashi-yaki (locally 'tamagoyaki') is dipped in dashi, with a flour and starch batter. Monja is tied to Tsukishima in Tokyo, with the name said to come from 'moji-yaki' and an Edo-period origin also claimed.", "Takoyaki: crisp outside, soft inside. Akashi-yaki: egg-soft.", "Street food.", "Warm dashi for Akashi-yaki dates only to about 1963 (Kobe Motomachi).", [["Aizuya: about", "https://www.aiduya.com/about/"], ["Akashi Tourism: Akashi-yaki", "https://www.yokoso-akashi.jp/akashi/akashi-yaki.html"], ["Go Tokyo: Tsukishima monja", "https://www.gotokyo.org/jp/spot/85/index.html"]]);
A("dish", "Tonkatsu & miso-katsu", "とんかつ・味噌カツ", [13, 23, 24], "Ginza's Rengatei (opened 1895) is the usual origin, with shredded cabbage and Worcester sauce in place of demi-glace, though some say the pork cutlet was not on the opening menu. 'Tonkatsu' appears as a name around 1930. Miso-katsu has no settled origin: street-stall dote-nabe, Yabaton, Mishodokanou's miso-katsu-don, and a claim from Tsu in Mie.", "Crisp and rich; miso-katsu sweet-salty.", "A staple of yoshoku.", "Look at the sauce to see the claim.", [["Otona no Shumatsu: tonkatsu history", "https://otonano-shumatsu.com/articles/284273"], ["Tokai TV: miso-katsu from Tsu", "https://www.tokai-tv.com/tokainews/feature/article_20230311_25852"], ["Misokatsu Kanou: history", "https://www.misokatu-kanou.com/history.html"]]);
A("dish", "Hitsumabushi", "ひつまぶし", [23], "Nagoya's chopped grilled eel on rice in a wooden tub, most often credited to Atsuta Houraiken (founded 1873). The standard way: split the rice into four, eat one plain, one with condiments (scallion, wasabi, nori), one as ochazuke with dashi or tea, and the fourth as you like.", "Rich, then fresh, then soothing.", "Eel lunch.", "Four parts, not three, is the usual advice.", [["Docomo: Atsuta Houraiken", "https://ichioshi.smt.docomo.ne.jp/articles/limited/21309"], ["Tabemaro: hitsumabushi", "https://www.tabemaro.jp/column/hitsumabushisuteppu/"]]);
A("dish", "Motsunabe & mizutaki", "もつ鍋・水炊き", [40], "Motsunabe is thought to come from coal-miners' offal and chives in soy, with another account tracing it to Korean residents' chilli-sesame-oil pot; one source dates it to the 1960s. Hakata mizutaki is credited to Hayashida Heizaburo of Nagasaki, who in 1905 combined Western consomme and Chinese baitang at 'Suigetsu'.", "Motsunabe: fatty and garlicky. Mizutaki: cloudy and clean.", "Winter hot pots.", "Dates are traditions, not records.", [["Wikipedia (ja): motsunabe", "https://ja.wikipedia.org/wiki/%E3%82%82%E3%81%A4%E9%8D%8B"], ["Hakata Kozuki: motsunabe", "https://www.hakata-kozuki.com/kyodoryori/motsunabe/"]]);
A("dish", "Goya champuru & rafute", "ゴーヤーチャンプルー・ラフテー", [47], "Goya came via China around the 15th century. Champuru stir-fries pork, tofu and vegetables, often flavoured with katsuobushi: pork and bonito together. Rafute is skin-on pork belly (or thigh) simmered in awamori and soy, said to descend from Ryukyu court cooking or Chinese dongpo pork. Okinawa's pork culture runs 'from the pig's start to its end'.", "Bitter, savoury; rafute rich and sweet-salty.", "Home cooking and banquets.", "Awamori simmering tenderises the pork.", [["MAFF: goya champuru", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/47_11_okinawa.html"], ["MAFF: rafute", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/47_6_okinawa.html"]]);
A("dish", "Tsukeage (satsuma-age)", "つけあげ（薩摩揚げ）", [46], "In Kagoshima called 'tsukeage'. One origin is Shimazu Nariakira, inspired by Kishu hanpen; another is the Ryukyu fried kamaboko 'chikiagi'. Kagoshima's is sweet, using sugar and the local ash-preserved sake (akumochi-zake).", "Sweet, fried fish paste.", "Home cooking and gifts.", "The sweetness matches Kagoshima's sugar-in-seasoning style.", [["Kagoshima City: tsukeage", "https://www.city.kagoshima.lg.jp/syokuiku/recipes/kyodo/aki/tsukeage.html"], ["MAFF: tsukeage", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/tsukeage_kagoshima.html"]]);
A("dish", "Taimeshi: Uwajima vs Matsuyama", "鯛めし（宇和島風・松山風）", [38], "Two Ehime dishes of the same name. In southern Ehime (Uwajima) raw sea bream sashimi dressed in a sauce is put on rice, with a story of Iyo naval crews eating it afloat. In the middle region (Matsuyama, Hojo) the bream is cooked with the rice in kombu dashi.", "Uwajima: silky, soy-egg sauce. Matsuyama: fragrant, steamed.", "Celebrations.", "Know which you are ordering.", [["Rurubu: two taimeshi", "https://plus.rurubu.jp/article/1k6f06vf0tt"], ["Food Discovery: taimeshi compared", "https://foodiscovery.jp/taimesi/"]]);
A("dish", "Sawachi ryori & katsuo tataki", "皿鉢料理・鰹のたたき", [39], "Sawachi ryori is a Tosa banquet of sashimi, tataki, sushi and simmered dishes on large platters (50 cm or more), tied to the 'okyaku' party culture. Tataki began, so the story goes, as a way to eat bonito past its freshness at sea. Straw flame searing is typical; salt tataki uses Kochi sun-dried salt.", "Smoky, garlicky, lean.", "Banquets and sakaba.", "The straw fire is a technique, not just decoration: it sears the surface fast.", [["MAFF: sawachi ryori", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/sawachiryori_kochi.html"], ["Kurashiru: katsuo tataki", "https://www.kurashiru.com/articles/f57706ab-2ee2-4335-95b4-7df78f1d6343"], ["Discover Japan: okyaku", "https://discoverjapan-web.com/article/153479"]]);
A("dish", "Surimi towns: Odawara, Sendai, Tottori", "蒲鉾（小田原・笹かま・とうふちくわ）", [14, 4, 31], "Odawara kamaboko traditionally uses white fish, especially guchi (croaker), washed repeatedly for fine, springy texture; the dates range from the Tenmei era to the Hojo period. Sendai's sasakama is attributed to the Meiji 30s, made from flounder, named by Abe Kamaboko after Date's bamboo-and-sparrow crest. Tottori's tofu-chikuwa is 7 parts tofu to 3 fish at one maker; the Edo domain lord is said to have recommended tofu.", "Springy fish cake; tofu-chikuwa soft and light.", "Oden, snacks, souvenirs.", "Sources disagree on the lord's name and on Odawara's dates.", [["MAFF: Odawara kamaboko", "https://www.maff.go.jp/j/keikaku/syokubunka/k_ryouri/search_menu/menu/35_19_kanagawa.html"], ["Kibun: sasakama history", "https://www.kibun.co.jp/brand/sasakama/history/index.html"], ["Tottori City: tofu chikuwa", "https://www.torican.jp/feature/toufu"]]);
A("dish", "Tsukudani of Tsukudajima", "佃煮（佃島）", [13], "Fishermen brought from Tsukuda village in Settsu (Osaka) by Tokugawa Ieyasu in 1603 (33 men, by one account) settled Tsukudajima in Edo. They preserved small unsold fish in soy and sugar. 29 June is Tsukudani Day, from the founding of Sumiyoshi Shrine in 1646.", "Salty-sweet and dense.", "Rice accompaniments.", "The Ieyasu story carries legend.", [["Thegate12: tsukudani", "https://thegate12.com/jp/article/251"], ["Osakana Suisankai: tsukudani", "https://osakana.suisankai.or.jp/business/9967"]]);

/* ---------- SUSHI ---------- */
A("sushi", "From narezushi to nigiri", "なれずしから握りへ", [25, 27, 13], "Sushi began as fermented fish packed in rice (narezushi, such as funa-zushi). Osaka's pressed hako-zushi dominated before Edo's nigiri, using vinegar rather than fermentation. Edomae sushi is vinegared, and Edo's sake-lees vinegar spread with it.", "Fermented, sour, or vinegar-bright depending on era.", "The line from Lake Biwa to Edo.", "'Edomae' origin dates run from 1680 to 1829 in sources.", [["Wikipedia (ja): Edomae sushi", "https://ja.wikipedia.org/wiki/%E6%B1%9F%E6%88%B8%E5%89%8D%E5%AF%BF%E5%8F%B8"], ["Sushiwalker: Edomae sushi", "https://sushiwalker.com/feature/85740/"]]);
A("sushi", "Osaka battera & hako-zushi", "バッテラ・箱寿司", [27], "Battera is pressed mackerel sushi from Osaka's Meiji era; the name is from the Portuguese 'bateira' (small boat). It was first made with konoshiro, then mackerel.", "Sweet-sour and firm.", "Pressed sushi.", "A wooden box or a mould shapes it.", [["Excite Recipe: battera", "https://erecipe.woman.excite.co.jp/article/E1596506217400/"], ["Osushi Studio: battera and oshizushi", "https://osushi.studio/media/battera-oshizushi-tsukurikata-guide/"]]);
A("sushi", "Kakinoha-zushi", "柿の葉寿司", [29], "Nara's festival sushi, over 200 years old: fish pressed on rice, wrapped in persimmon leaf and weighted. The leaf's tannin is antibacterial.", "Subtle leaf perfume.", "Festival and gift sushi.", "Eat after resting so the leaf can flavour the rice.", [["Hugkum: kakinoha-zushi", "https://hugkum.sho.jp/520675"]]);
A("sushi", "Toyama masu-zushi", "鱒寿司", [16], "Pressed, unfermented sushi (a hayazushi) of cherry trout (sakura-masu) from the Jinzu river area. A story links it to a gift to Yoshimune, though the Wikipedia article treats it as a popular account.", "Clean and lightly sour.", "Ekiben and gifts.", "Cut through the bamboo-leaf wrapper with the thread.", [["Wikipedia (ja): masu-zushi", "https://ja.wikipedia.org/wiki/%E9%B1%92%E5%AF%BF%E5%8F%B8"], ["Osushi Studio: regional sushi", "https://osushi.studio/media/kyodo-sushi-gotochi-zenkoku/"]]);

/* ---------- VEGETABLES, CITRUS & AROMATICS ---------- */
A("veg", "Kyo-yasai", "京野菜", [26], "Kyoto defined 'Kyo no dento yasai' in 1988 (some say 1987): vegetables grown in Kyoto before the Meiji era, about 37-40 items. Of these, those meeting stricter standards are 'Kyoto brand' produce, 19 items. Shogoin daikon, Kamo eggplant and Kujo negi are named examples.", "Soft, sweet, delicate.", "Kaiseki and shojin cooking.", "Counts vary by source.", [["Kyoto Travel: kyo-yasai", "https://plus.kyoto.travel/entry/kyoyasai_kihon"], ["Kentei: kyo-yasai", "https://kentei-study.jugem.jp/?eid=21"], ["Agriture: Kyoto vegetables", "https://agriture.jp/local-veg/kyoto/"]]);
A("veg", "Kaga yasai", "加賀野菜", [17], "Fifteen vegetables certified by the Kanazawa agricultural brand association, grown since before 1945 mainly in the prefecture. Examples: Kaga renkon, kintoki-so, Gensuke daikon, Kaga futo-kyuri and Gorojima kintoki.", "Rooted in Kanazawa's winter cooking.", "Jibu-ni, simmered dishes.", "Certification covers the Kanazawa area.", [["Wikipedia (ja): Kaga yasai", "https://ja.wikipedia.org/wiki/%E5%8A%A0%E8%B3%80%E9%87%8E%E8%8F%9C"], ["Agriture: Hokuriku vegetables", "https://agriture.jp/sustainable/hokuriku-traditional-vegetables/"]]);
A("veg", "Negi: white in the east, green in the west", "ねぎ（根深ねぎと葉ねぎ）", [11, 10, 26], "The Kanto grows white (nebuka) negi eaten for the white sheath, mostly Senju-type; Fukaya in Saitama is the famous name, though other varieties are now grown. Kansai grows green leaf negi, of which Kujo negi of Kyoto is the leading example. Gunma's thick Shimonita negi is another family.", "White: sweet when cooked. Green: soft and fragrant.", "Soba condiments, nabe, yakitori.", "'Aonegi' in Kansai means leaf negi generally.", [["Olive Hitomawashi: negi east and west", "https://www.olive-hitomawashi.com/column/2017/08/post-287.html"], ["Rassic: green vs white negi", "https://rassic.jp/content/470"], ["Agriture: Kujo negi", "https://agriture.jp/kyoto-vegetables/kujo-onion/"]]);
A("veg", "Kabosu", "かぼす", [44], "Oita grows about 98-99% of Japan's kabosu (98.5% in 2018).", "Mild, mellow acidity.", "Squeezed on fish, shochu mixers, nabe.", "Larger and rounder than sudachi.", [["Urahyoji: kabosu", "https://urahyoji.com/crops-sudachi/"], ["Oita Prefecture: kabosu vs sudachi", "https://edit.pref.oita.jp/news-columns/1421/"]]);
A("veg", "Mikan", "みかん", [30, 38, 43], "Wakayama has been first for 22 straight years (145,200 t, 22.1% in the 2025 crop), Ehime returned to second (121,800 t, about 19%) and Kumamoto is fourth at about 12%. The national crop was 656,300 t.", "Sweet-tart.", "Eating citrus.", "Ehime's mikan culture dates from the late Edo period at Yoshida, Uwajima.", [["Nouka Fruits: mikan 2025", "https://nouka-fruits.com/mikan-ranking-seisanryou-2025/"], ["Ehime Prefecture: mikan", "https://www.pref.ehime.jp/uploaded/attachment/74163.pdf"]]);
A("veg", "Shichimi: three great blends", "七味唐辛子（三大七味）", [13, 20, 26], "Yagenbori (Asakusa), Yawataya Isogoro (Zenkoji, selling since 1736; includes ginger) and Shichimiya Honpo (Kiyomizu, Kyoto, with fragrant ingredients). The only fixed rule is seven ingredients. The beginning is variously dated to around 1625.", "Heat with citrus, sesame and sansho.", "Soba, udon, nabe.", "Compare the three side by side.", [["Mi-journey: three great shichimi", "https://mi-journey.jp/foodie/90695/"], ["Yawataya: history", "https://www.yawataya.co.jp/about/history/02.php"], ["Shichimiya: three capitals story", "https://www.shichimiya.co.jp/shichimi-santo-story"]]);
A("veg", "Budo sansho", "ぶどう山椒", [30], "Wakayama grows 60-70% of Japan's sansho, with Aridagawa (formerly Shimizu) the chief area; the budo variety was found in the late Edo period at Toi. One year's table gave Wakayama 440.5 t and Kochi 134.2 t. Farmers are ageing: an average of 79.", "Strong aroma and numbing heat.", "Grilled eel, sansho-jako, spice.", "A famous producing region at risk.", [["Wakayama Shimpo: budo sansho", "https://wakayamashimpo.co.jp/2021/08/20210803_103111.html"], ["Aridagawa Town: budo sansho", "https://www.town.aridagawa.lg.jp/ijuu/tokusei/5603.html"]]);

/* ---------- RICE ---------- */
A("rice", "Koshihikari", "コシヒカリ", [15, 8, 9], "33.1% of the 2023 crop and first since 1979 (36.2% at the 2016 peak). Mainly Niigata, Ibaraki and Tochigi. In Fukui it is 50.2% of the crop (Hanaechizen 26.4%, Akisakari 9.2%); in Shimane 50.0% (Kinumusume 36.6%, Tsuyahime 11.0%).", "Sweet, sticky, aromatic.", "Table rice.", "Check the prefecture's own mix before generalising.", [["Komenet: variety share", "https://www.komenet.jp/pdf/R05sakutuke.pdf"], ["MAFF: Hokuriku varieties", "https://www.maff.go.jp/j/pr/aff/1601/pdf/1601_04.pdf"]]);
A("rice", "Hitomebore", "ひとめぼれ", [4, 3, 7], "8.3% of the 2023 crop, grown mainly in Miyagi, Iwate and Fukushima.", "Soft, balanced.", "Table rice.", "Second in acreage nationally.", [["Komenet: variety share", "https://www.komenet.jp/pdf/R05sakutuke.pdf"], ["Komenet FAQ: varieties", "https://www.komenet.jp/faq/ot_hinshu.html"]]);
A("rice", "Hinohikari", "ヒノヒカリ", [43, 44, 46], "7.4% of the 2023 crop, the most-grown variety in Kyushu (Kumamoto, Oita, Kagoshima) and third nationally.", "Plump, mild.", "Table rice in the south.", "Kyushu's default.", [["Komenet: variety share", "https://www.komenet.jp/pdf/R05sakutuke.pdf"]]);
A("rice", "Akitakomachi", "あきたこまち", [5], "6.7% of the 2023 crop and fourth in acreage.", "Light and sticky.", "Table rice.", "Akita's signature.", [["Komenet: variety share", "https://www.komenet.jp/pdf/R05sakutuke.pdf"]]);

/* ---------- TEA ---------- */
A("tea", "Production: Kagoshima vs Shizuoka", "荒茶生産量", [46, 22, 24], "In 2024 Kagoshima led crude tea (27,000 t) over Shizuoka (25,800 t). In the 2025 first flush Shizuoka fell 19% to 8,120 t, its lowest, and came second for the first time. Mie was third in 2020 at 5,080 t, and Kyoto fifth in 2023 at 2,640 t. Totals mix every type of tea.", "-", "Reading statistics.", "Rankings flip from year to year.", [["Nikkei: Kagoshima first in first flush", "https://www.nikkei.com/article/DGXZQOCC2053U0Q5A820C2000000/"], ["Sanrokuen: tea output 2024", "https://tea-sanrokuen.com/wp/archives/1807"], ["Senchado: tea by prefecture", "https://shop.senchado.jp/blogs/ocha/20210802_218"]]);
A("tea", "Shading: sencha, kabusecha, gyokuro, matcha", "被覆栽培", [26, 24, 40], "Gyokuro bushes are covered about 20 days; kabusecha about a week with less shading; tencha (the leaf for matcha) is grown shaded too, steamed and dried without rolling, then stone-ground. Sencha is grown in the open. Longer shading keeps more theanine (umami) and less catechin (astringency).", "Gyokuro: deep umami. Sencha: balance of sweet and astringent.", "Gyokuro in low-temperature brewing, matcha for tea ceremony.", "Mie is a main kabusecha area.", [["E-cha: shaded cultivation", "https://www.e-cha.co.jp/contents/hifuku-saibai/"], ["Senchado: tea types", "https://shop.senchado.jp/blogs/ocha/20200208_416"], ["Uji tea: tea types", "https://ujicha.or.jp/knowledge/kinds/"]]);
A("tea", "Shizuoka: fukamushi & mountain tea", "静岡茶", [22], "Flatland Makinohara and Kakegawa make deep-steamed (fukamushi) tea with a dark colour and deep body. Mountain areas such as Kawane and Honyama produce fragrant lightly steamed tea.", "Deep-steamed: rich, thick. Mountain: floral.", "Everyday sencha.", "Fukamushi leaves are broken and cloudy by design.", [["E-cha: tea regions", "https://www.e-cha.co.jp/contents/japanesetea-producing-area/"], ["Senchado: top 5 tea regions", "https://shop.senchado.jp/blogs/ocha/20200727_382"]]);
A("tea", "Kagoshima: toward tencha", "鹿児島茶", [46], "Warm climate and large mechanised farms. Matcha demand is pushing growers from sencha to tencha.", "Mild, sweet.", "Sencha, tencha.", "Chiran tea is sometimes added to the 'three great teas'.", [["Denken: Kagoshima tea", "https://denken-test.jp/culture_industry/2849/"], ["Minorien: tea regions", "https://minorien.jp/chishiki/chasanchi.html"]]);
A("tea", "Uji matcha", "宇治抹茶", [26], "Uji is one of the three famed teas, with matcha as its signature: tencha ground into powder.", "Sweet, vegetal, deep.", "Tea ceremony and sweets.", "Counted with Shizuoka and Sayama as the 'three famous teas'.", [["Uji Tea Association", "https://ujicha.or.jp/knowledge/kinds/"], ["E-cha: tea regions", "https://www.e-cha.co.jp/contents/japanesetea-producing-area/"]]);
A("tea", "Sayama: the strong roast", "狭山茶", [11], "Mainly sencha, finished with 'Sayama-biire', a strong roasting that brings a toasty aroma and rich sweetness.", "Toasty, sweet.", "Sencha.", "Output is small despite the fame.", [["E-cha: tea regions", "https://www.e-cha.co.jp/contents/japanesetea-producing-area/"], ["Senchado: top 5 tea regions", "https://shop.senchado.jp/blogs/ocha/20200727_382"]]);
A("tea", "Ureshino & Yame", "嬉野茶・八女茶", [41, 40], "Ureshino (Saga) makes both steamed tea and kamairi (pan-fired) tea, which has a roasted fragrance. Yame (Fukuoka) is famous for gyokuro, shaded from mid-April and picked late April to late May; one source puts its share of national tea at about 3%.", "Kamairi: toasty. Gyokuro: dense umami.", "Gyokuro, kamairi.", "Pan-fired tea is China-derived.", [["E-cha: Yame tea", "https://www.e-cha.co.jp/contents/yame-cha/"], ["Yamamotoyama: Yame tea", "https://yamamotoyama.co.jp/blogs/column/reading050"], ["Senchado: tea types", "https://shop.senchado.jp/blogs/ocha/20200727_382"]]);

/* ---------- TOFU, YUBA, KONNYAKU ---------- */
A("soy", "Momen vs kinugoshi tofu", "木綿豆腐と絹ごし豆腐", [26], "Momen is made by breaking the curd, pressing out water and setting it again; kinugoshi sets thicker soy milk in one go. The name 'momen' (cotton) comes from the cloth pattern left behind. Momen carries 20-30% more protein, calcium and iron because the water is pressed out. Kyoto's Nanzenji yudofu goes back to Edo-period simmered tofu, boiled in kombu dashi, often using a firm white tofu that holds its shape.", "Momen: firm and soy-forward. Kinugoshi: silky.", "Yudofu, nabe, miso soup.", "Choose firmness for the dish.", [["Orange Page: momen vs kinugoshi", "https://www.orangepage.net/food/basics-cooking/hatena/111671"], ["Tokyo Gas: momen vs kinugoshi", "https://uchi.tokyo-gas.co.jp/topics/3630"], ["Serai: Nanzenji yudofu", "https://serai.jp/gourmet/1202487"]]);
A("soy", "Kyo-yuba & kyo-fu", "京湯葉・京麩", [26], "Yuba came from China in the Kamakura period for shojin cooking and reached tea-kaiseki by Muromachi's Tensho era, favoured by Sen no Rikyu. Kyo-yuba is fresh and dried. Hanbee-fu began in 1689 (Genroku 2), and Rikyu-fu (Daitokuji-fu) is a deep-fried nama-fu.", "Yuba: creamy; fu: chewy and mild.", "Shojin and kaiseki dishes.", "Kyo-ryori is intangible heritage-registered.", [["MAFF: kyo-yuba", "https://www.maff.go.jp/j/keikaku/syokubunka/traditional-foods/menu/kyo_yuba.html"], ["Keihan: shojin ryori", "https://www.keihan.co.jp/navi/kyoto_tsu/tsu201906.html"]]);
A("soy", "Shima-dofu", "島豆腐", [47], "Okinawan tofu is harder and chewier than momen: it is pressed for 2-4 hours against about 30 minutes for ordinary momen. Yushi-dofu is the soft, unpressed stage before moulding.", "Dense, bean-forward.", "Champuru and soup.", "Pressing time is the difference.", [["Macaroni: shima-dofu", "https://macaro-ni.jp/47925"], ["Orion: shima-dofu", "https://www.orionbeer.co.jp/story/shima-dofu/"]]);
A("soy", "Gunma konnyaku", "群馬のこんにゃく", [10], "Gunma produces more than 90% of Japan's konjac tubers: 50,200 t of 53,700 t in 2020 (93.5%), about 42,000 t in 2022.", "Neutral, springy.", "Oden, sukiyaki, sashimi konnyaku.", "Year-by-year totals vary.", [["MAFF: konnyaku status", "https://www.maff.go.jp/j/seisan/tokusan/attach/pdf/konnyaku-17.pdf"], ["Gunma Prefecture: konnyaku", "https://www.pref.gunma.jp/page/15530.html"]]);

/* ---------- ORDER LAYERS ---------- */
const ORDER = ["fish", "seafood", "dish", "sushi", "shoyu", "miso", "dashi", "salt", "veg", "rice", "tea", "soy", "ramen", "noodle", "meat", "seaweed", "pickles", "sweets", "sake", "shochu", "whisky"];
CATS.sort((a, b) => ORDER.indexOf(a.id) - ORDER.indexOf(b.id));
